-- Generado por scripts/derive_catalogs.py desde data/raw/data (StatsBomb open-data).
-- No editar a mano: regenérase con uv run --project data-platform python -m scripts.derive_catalogs
-- country
INSERT INTO oltp.country (country_id, country_name) VALUES (3, 'Albania');
INSERT INTO oltp.country (country_id, country_name) VALUES (4, 'Algeria');
INSERT INTO oltp.country (country_id, country_name) VALUES (6, 'Andorra');
INSERT INTO oltp.country (country_id, country_name) VALUES (7, 'Angola');
INSERT INTO oltp.country (country_id, country_name) VALUES (11, 'Argentina');
INSERT INTO oltp.country (country_id, country_name) VALUES (12, 'Armenia');
INSERT INTO oltp.country (country_id, country_name) VALUES (14, 'Australia');
INSERT INTO oltp.country (country_id, country_name) VALUES (15, 'Austria');
INSERT INTO oltp.country (country_id, country_name) VALUES (16, 'Azerbaijan');
INSERT INTO oltp.country (country_id, country_name) VALUES (18, 'Bahrain');
INSERT INTO oltp.country (country_id, country_name) VALUES (21, 'Belarus');
INSERT INTO oltp.country (country_id, country_name) VALUES (22, 'Belgium');
INSERT INTO oltp.country (country_id, country_name) VALUES (24, 'Benin');
INSERT INTO oltp.country (country_id, country_name) VALUES (25, 'Bermuda');
INSERT INTO oltp.country (country_id, country_name) VALUES (26, 'Bhutan');
INSERT INTO oltp.country (country_id, country_name) VALUES (27, 'Bolivia');
INSERT INTO oltp.country (country_id, country_name) VALUES (28, 'Bosnia and Herzegovina');
INSERT INTO oltp.country (country_id, country_name) VALUES (31, 'Brazil');
INSERT INTO oltp.country (country_id, country_name) VALUES (35, 'Bulgaria');
INSERT INTO oltp.country (country_id, country_name) VALUES (36, 'Burkina Faso');
INSERT INTO oltp.country (country_id, country_name) VALUES (37, 'Burundi');
INSERT INTO oltp.country (country_id, country_name) VALUES (39, 'Cameroon');
INSERT INTO oltp.country (country_id, country_name) VALUES (40, 'Canada');
INSERT INTO oltp.country (country_id, country_name) VALUES (41, 'Cape Verde');
INSERT INTO oltp.country (country_id, country_name) VALUES (43, 'Central African Republic');
INSERT INTO oltp.country (country_id, country_name) VALUES (44, 'Chad');
INSERT INTO oltp.country (country_id, country_name) VALUES (45, 'Chile');
INSERT INTO oltp.country (country_id, country_name) VALUES (46, 'China');
INSERT INTO oltp.country (country_id, country_name) VALUES (49, 'Colombia');
INSERT INTO oltp.country (country_id, country_name) VALUES (50, 'Comoros');
INSERT INTO oltp.country (country_id, country_name) VALUES (51, 'Congo (Brazzaville)');
INSERT INTO oltp.country (country_id, country_name) VALUES (52, 'Congo, (Kinshasa)');
INSERT INTO oltp.country (country_id, country_name) VALUES (54, 'Costa Rica');
INSERT INTO oltp.country (country_id, country_name) VALUES (55, 'Côte d''Ivoire');
INSERT INTO oltp.country (country_id, country_name) VALUES (56, 'Croatia');
INSERT INTO oltp.country (country_id, country_name) VALUES (58, 'Curaçao');
INSERT INTO oltp.country (country_id, country_name) VALUES (60, 'Czech Republic');
INSERT INTO oltp.country (country_id, country_name) VALUES (61, 'Denmark');
INSERT INTO oltp.country (country_id, country_name) VALUES (64, 'Dominican Republic');
INSERT INTO oltp.country (country_id, country_name) VALUES (65, 'Ecuador');
INSERT INTO oltp.country (country_id, country_name) VALUES (66, 'Egypt');
INSERT INTO oltp.country (country_id, country_name) VALUES (67, 'El Salvador');
INSERT INTO oltp.country (country_id, country_name) VALUES (68, 'England');
INSERT INTO oltp.country (country_id, country_name) VALUES (69, 'Equatorial Guinea');
INSERT INTO oltp.country (country_id, country_name) VALUES (71, 'Estonia');
INSERT INTO oltp.country (country_id, country_name) VALUES (72, 'Ethiopia');
INSERT INTO oltp.country (country_id, country_name) VALUES (73, 'Europe');
INSERT INTO oltp.country (country_id, country_name) VALUES (76, 'Fiji');
INSERT INTO oltp.country (country_id, country_name) VALUES (77, 'Finland');
INSERT INTO oltp.country (country_id, country_name) VALUES (78, 'France');
INSERT INTO oltp.country (country_id, country_name) VALUES (79, 'French Guiana');
INSERT INTO oltp.country (country_id, country_name) VALUES (82, 'Gabon');
INSERT INTO oltp.country (country_id, country_name) VALUES (83, 'Gambia');
INSERT INTO oltp.country (country_id, country_name) VALUES (84, 'Georgia');
INSERT INTO oltp.country (country_id, country_name) VALUES (85, 'Germany');
INSERT INTO oltp.country (country_id, country_name) VALUES (86, 'Ghana');
INSERT INTO oltp.country (country_id, country_name) VALUES (87, 'Gibraltar');
INSERT INTO oltp.country (country_id, country_name) VALUES (88, 'Greece');
INSERT INTO oltp.country (country_id, country_name) VALUES (90, 'Grenada');
INSERT INTO oltp.country (country_id, country_name) VALUES (91, 'Guadeloupe');
INSERT INTO oltp.country (country_id, country_name) VALUES (93, 'Guatemala');
INSERT INTO oltp.country (country_id, country_name) VALUES (95, 'Guinea');
INSERT INTO oltp.country (country_id, country_name) VALUES (96, 'Guinea-Bissau');
INSERT INTO oltp.country (country_id, country_name) VALUES (97, 'Guyana');
INSERT INTO oltp.country (country_id, country_name) VALUES (98, 'Haiti');
INSERT INTO oltp.country (country_id, country_name) VALUES (101, 'Honduras');
INSERT INTO oltp.country (country_id, country_name) VALUES (103, 'Hungary');
INSERT INTO oltp.country (country_id, country_name) VALUES (104, 'Iceland');
INSERT INTO oltp.country (country_id, country_name) VALUES (105, 'India');
INSERT INTO oltp.country (country_id, country_name) VALUES (107, 'Iran, Islamic Republic of');
INSERT INTO oltp.country (country_id, country_name) VALUES (108, 'Iraq');
INSERT INTO oltp.country (country_id, country_name) VALUES (109, 'Ireland');
INSERT INTO oltp.country (country_id, country_name) VALUES (111, 'Israel');
INSERT INTO oltp.country (country_id, country_name) VALUES (112, 'Italy');
INSERT INTO oltp.country (country_id, country_name) VALUES (113, 'Jamaica');
INSERT INTO oltp.country (country_id, country_name) VALUES (114, 'Japan');
INSERT INTO oltp.country (country_id, country_name) VALUES (117, 'Kazakhstan');
INSERT INTO oltp.country (country_id, country_name) VALUES (118, 'Kenya');
INSERT INTO oltp.country (country_id, country_name) VALUES (120, 'Korea (North)');
INSERT INTO oltp.country (country_id, country_name) VALUES (121, 'Korea (South)');
INSERT INTO oltp.country (country_id, country_name) VALUES (122, 'Kosovo');
INSERT INTO oltp.country (country_id, country_name) VALUES (124, 'Kyrgyzstan');
INSERT INTO oltp.country (country_id, country_name) VALUES (125, 'Lao PDR');
INSERT INTO oltp.country (country_id, country_name) VALUES (126, 'Latvia');
INSERT INTO oltp.country (country_id, country_name) VALUES (130, 'Libya');
INSERT INTO oltp.country (country_id, country_name) VALUES (131, 'Liechtenstein');
INSERT INTO oltp.country (country_id, country_name) VALUES (132, 'Lithuania');
INSERT INTO oltp.country (country_id, country_name) VALUES (133, 'Luxembourg');
INSERT INTO oltp.country (country_id, country_name) VALUES (135, 'Macedonia, Republic of');
INSERT INTO oltp.country (country_id, country_name) VALUES (136, 'Madagascar');
INSERT INTO oltp.country (country_id, country_name) VALUES (138, 'Malaysia');
INSERT INTO oltp.country (country_id, country_name) VALUES (140, 'Mali');
INSERT INTO oltp.country (country_id, country_name) VALUES (141, 'Malta');
INSERT INTO oltp.country (country_id, country_name) VALUES (143, 'Martinique');
INSERT INTO oltp.country (country_id, country_name) VALUES (144, 'Mauritania');
INSERT INTO oltp.country (country_id, country_name) VALUES (145, 'Mauritius');
INSERT INTO oltp.country (country_id, country_name) VALUES (147, 'Mexico');
INSERT INTO oltp.country (country_id, country_name) VALUES (149, 'Moldova');
INSERT INTO oltp.country (country_id, country_name) VALUES (150, 'Monaco');
INSERT INTO oltp.country (country_id, country_name) VALUES (152, 'Montenegro');
INSERT INTO oltp.country (country_id, country_name) VALUES (154, 'Morocco');
INSERT INTO oltp.country (country_id, country_name) VALUES (155, 'Mozambique');
INSERT INTO oltp.country (country_id, country_name) VALUES (157, 'Namibia');
INSERT INTO oltp.country (country_id, country_name) VALUES (159, 'Nepal');
INSERT INTO oltp.country (country_id, country_name) VALUES (160, 'Netherlands');
INSERT INTO oltp.country (country_id, country_name) VALUES (162, 'New Caledonia');
INSERT INTO oltp.country (country_id, country_name) VALUES (163, 'New Zealand');
INSERT INTO oltp.country (country_id, country_name) VALUES (166, 'Nigeria');
INSERT INTO oltp.country (country_id, country_name) VALUES (169, 'Northern Ireland');
INSERT INTO oltp.country (country_id, country_name) VALUES (171, 'Norway');
INSERT INTO oltp.country (country_id, country_name) VALUES (176, 'Panama');
INSERT INTO oltp.country (country_id, country_name) VALUES (178, 'Paraguay');
INSERT INTO oltp.country (country_id, country_name) VALUES (179, 'Peru');
INSERT INTO oltp.country (country_id, country_name) VALUES (180, 'Philippines');
INSERT INTO oltp.country (country_id, country_name) VALUES (182, 'Poland');
INSERT INTO oltp.country (country_id, country_name) VALUES (183, 'Portugal');
INSERT INTO oltp.country (country_id, country_name) VALUES (184, 'Puerto Rico');
INSERT INTO oltp.country (country_id, country_name) VALUES (185, 'Qatar');
INSERT INTO oltp.country (country_id, country_name) VALUES (187, 'Romania');
INSERT INTO oltp.country (country_id, country_name) VALUES (188, 'Russia');
INSERT INTO oltp.country (country_id, country_name) VALUES (189, 'Rwanda');
INSERT INTO oltp.country (country_id, country_name) VALUES (198, 'San Marino');
INSERT INTO oltp.country (country_id, country_name) VALUES (200, 'Saudi Arabia');
INSERT INTO oltp.country (country_id, country_name) VALUES (201, 'Scotland');
INSERT INTO oltp.country (country_id, country_name) VALUES (202, 'Senegal');
INSERT INTO oltp.country (country_id, country_name) VALUES (203, 'Serbia');
INSERT INTO oltp.country (country_id, country_name) VALUES (205, 'Sierra Leone');
INSERT INTO oltp.country (country_id, country_name) VALUES (207, 'Slovakia');
INSERT INTO oltp.country (country_id, country_name) VALUES (208, 'Slovenia');
INSERT INTO oltp.country (country_id, country_name) VALUES (210, 'Somalia');
INSERT INTO oltp.country (country_id, country_name) VALUES (211, 'South Africa');
INSERT INTO oltp.country (country_id, country_name) VALUES (214, 'Spain');
INSERT INTO oltp.country (country_id, country_name) VALUES (216, 'Sudan');
INSERT INTO oltp.country (country_id, country_name) VALUES (217, 'Suriname');
INSERT INTO oltp.country (country_id, country_name) VALUES (220, 'Sweden');
INSERT INTO oltp.country (country_id, country_name) VALUES (221, 'Switzerland');
INSERT INTO oltp.country (country_id, country_name) VALUES (222, 'Syrian Arab Republic (Syria)');
INSERT INTO oltp.country (country_id, country_name) VALUES (225, 'Tanzania, United Republic of');
INSERT INTO oltp.country (country_id, country_name) VALUES (226, 'Thailand');
INSERT INTO oltp.country (country_id, country_name) VALUES (228, 'Togo');
INSERT INTO oltp.country (country_id, country_name) VALUES (231, 'Trinidad and Tobago');
INSERT INTO oltp.country (country_id, country_name) VALUES (232, 'Tunisia');
INSERT INTO oltp.country (country_id, country_name) VALUES (233, 'Turkey');
INSERT INTO oltp.country (country_id, country_name) VALUES (237, 'Uganda');
INSERT INTO oltp.country (country_id, country_name) VALUES (238, 'Ukraine');
INSERT INTO oltp.country (country_id, country_name) VALUES (239, 'United Arab Emirates');
INSERT INTO oltp.country (country_id, country_name) VALUES (241, 'United States of America');
INSERT INTO oltp.country (country_id, country_name) VALUES (242, 'Uruguay');
INSERT INTO oltp.country (country_id, country_name) VALUES (244, 'Uzbekistan');
INSERT INTO oltp.country (country_id, country_name) VALUES (246, 'Venezuela (Bolivarian Republic)');
INSERT INTO oltp.country (country_id, country_name) VALUES (247, 'Vietnam');
INSERT INTO oltp.country (country_id, country_name) VALUES (249, 'Wales');
INSERT INTO oltp.country (country_id, country_name) VALUES (253, 'Zambia');
INSERT INTO oltp.country (country_id, country_name) VALUES (254, 'Zimbabwe');
INSERT INTO oltp.country (country_id, country_name) VALUES (255, 'International');
-- competition_stage
INSERT INTO oltp.competition_stage (competition_stage_id, competition_stage_name) VALUES (1, 'Regular Season');
INSERT INTO oltp.competition_stage (competition_stage_id, competition_stage_name) VALUES (10, 'Group Stage');
INSERT INTO oltp.competition_stage (competition_stage_id, competition_stage_name) VALUES (11, 'Quarter-finals');
INSERT INTO oltp.competition_stage (competition_stage_id, competition_stage_name) VALUES (15, 'Semi-finals');
INSERT INTO oltp.competition_stage (competition_stage_id, competition_stage_name) VALUES (25, '3rd Place Final');
INSERT INTO oltp.competition_stage (competition_stage_id, competition_stage_name) VALUES (26, 'Final');
INSERT INTO oltp.competition_stage (competition_stage_id, competition_stage_name) VALUES (33, 'Round of 16');
INSERT INTO oltp.competition_stage (competition_stage_id, competition_stage_name) VALUES (34, '1st Round');
INSERT INTO oltp.competition_stage (competition_stage_id, competition_stage_name) VALUES (42, 'Apertura');
INSERT INTO oltp.competition_stage (competition_stage_id, competition_stage_name) VALUES (69, 'Championship Round');
INSERT INTO oltp.competition_stage (competition_stage_id, competition_stage_name) VALUES (74, 'Championship - Final');
INSERT INTO oltp.competition_stage (competition_stage_id, competition_stage_name) VALUES (99, '1st Group Stage');
INSERT INTO oltp.competition_stage (competition_stage_id, competition_stage_name) VALUES (102, '1st Round ');
INSERT INTO oltp.competition_stage (competition_stage_id, competition_stage_name) VALUES (143, 'Relegation Play-offs');
INSERT INTO oltp.competition_stage (competition_stage_id, competition_stage_name) VALUES (158, 'Play-offs - Semi-Finals');
-- event_type
INSERT INTO oltp.event_type (event_type_id, event_type_name) VALUES (2, 'Ball Recovery');
INSERT INTO oltp.event_type (event_type_id, event_type_name) VALUES (3, 'Dispossessed');
INSERT INTO oltp.event_type (event_type_id, event_type_name) VALUES (4, 'Duel');
INSERT INTO oltp.event_type (event_type_id, event_type_name) VALUES (5, 'Camera On');
INSERT INTO oltp.event_type (event_type_id, event_type_name) VALUES (6, 'Block');
INSERT INTO oltp.event_type (event_type_id, event_type_name) VALUES (8, 'Offside');
INSERT INTO oltp.event_type (event_type_id, event_type_name) VALUES (9, 'Clearance');
INSERT INTO oltp.event_type (event_type_id, event_type_name) VALUES (10, 'Interception');
INSERT INTO oltp.event_type (event_type_id, event_type_name) VALUES (14, 'Dribble');
INSERT INTO oltp.event_type (event_type_id, event_type_name) VALUES (16, 'Shot');
INSERT INTO oltp.event_type (event_type_id, event_type_name) VALUES (17, 'Pressure');
INSERT INTO oltp.event_type (event_type_id, event_type_name) VALUES (18, 'Half Start');
INSERT INTO oltp.event_type (event_type_id, event_type_name) VALUES (19, 'Substitution');
INSERT INTO oltp.event_type (event_type_id, event_type_name) VALUES (20, 'Own Goal Against');
INSERT INTO oltp.event_type (event_type_id, event_type_name) VALUES (21, 'Foul Won');
INSERT INTO oltp.event_type (event_type_id, event_type_name) VALUES (22, 'Foul Committed');
INSERT INTO oltp.event_type (event_type_id, event_type_name) VALUES (23, 'Goal Keeper');
INSERT INTO oltp.event_type (event_type_id, event_type_name) VALUES (24, 'Bad Behaviour');
INSERT INTO oltp.event_type (event_type_id, event_type_name) VALUES (25, 'Own Goal For');
INSERT INTO oltp.event_type (event_type_id, event_type_name) VALUES (26, 'Player On');
INSERT INTO oltp.event_type (event_type_id, event_type_name) VALUES (27, 'Player Off');
INSERT INTO oltp.event_type (event_type_id, event_type_name) VALUES (28, 'Shield');
INSERT INTO oltp.event_type (event_type_id, event_type_name) VALUES (29, 'Camera off');
INSERT INTO oltp.event_type (event_type_id, event_type_name) VALUES (30, 'Pass');
INSERT INTO oltp.event_type (event_type_id, event_type_name) VALUES (33, '50/50');
INSERT INTO oltp.event_type (event_type_id, event_type_name) VALUES (34, 'Half End');
INSERT INTO oltp.event_type (event_type_id, event_type_name) VALUES (35, 'Starting XI');
INSERT INTO oltp.event_type (event_type_id, event_type_name) VALUES (36, 'Tactical Shift');
INSERT INTO oltp.event_type (event_type_id, event_type_name) VALUES (37, 'Error');
INSERT INTO oltp.event_type (event_type_id, event_type_name) VALUES (38, 'Miscontrol');
INSERT INTO oltp.event_type (event_type_id, event_type_name) VALUES (39, 'Dribbled Past');
INSERT INTO oltp.event_type (event_type_id, event_type_name) VALUES (40, 'Injury Stoppage');
INSERT INTO oltp.event_type (event_type_id, event_type_name) VALUES (41, 'Referee Ball-Drop');
INSERT INTO oltp.event_type (event_type_id, event_type_name) VALUES (42, 'Ball Receipt*');
INSERT INTO oltp.event_type (event_type_id, event_type_name) VALUES (43, 'Carry');
-- play_pattern
INSERT INTO oltp.play_pattern (play_pattern_id, play_pattern_name) VALUES (1, 'Regular Play');
INSERT INTO oltp.play_pattern (play_pattern_id, play_pattern_name) VALUES (2, 'From Corner');
INSERT INTO oltp.play_pattern (play_pattern_id, play_pattern_name) VALUES (3, 'From Free Kick');
INSERT INTO oltp.play_pattern (play_pattern_id, play_pattern_name) VALUES (4, 'From Throw In');
INSERT INTO oltp.play_pattern (play_pattern_id, play_pattern_name) VALUES (5, 'Other');
INSERT INTO oltp.play_pattern (play_pattern_id, play_pattern_name) VALUES (6, 'From Counter');
INSERT INTO oltp.play_pattern (play_pattern_id, play_pattern_name) VALUES (7, 'From Goal Kick');
INSERT INTO oltp.play_pattern (play_pattern_id, play_pattern_name) VALUES (8, 'From Keeper');
INSERT INTO oltp.play_pattern (play_pattern_id, play_pattern_name) VALUES (9, 'From Kick Off');
-- position
INSERT INTO oltp.position (position_id, position_name) VALUES (0, 'Substitute');
INSERT INTO oltp.position (position_id, position_name) VALUES (1, 'Goalkeeper');
INSERT INTO oltp.position (position_id, position_name) VALUES (2, 'Right Back');
INSERT INTO oltp.position (position_id, position_name) VALUES (3, 'Right Center Back');
INSERT INTO oltp.position (position_id, position_name) VALUES (4, 'Center Back');
INSERT INTO oltp.position (position_id, position_name) VALUES (5, 'Left Center Back');
INSERT INTO oltp.position (position_id, position_name) VALUES (6, 'Left Back');
INSERT INTO oltp.position (position_id, position_name) VALUES (7, 'Right Wing Back');
INSERT INTO oltp.position (position_id, position_name) VALUES (8, 'Left Wing Back');
INSERT INTO oltp.position (position_id, position_name) VALUES (9, 'Right Defensive Midfield');
INSERT INTO oltp.position (position_id, position_name) VALUES (10, 'Center Defensive Midfield');
INSERT INTO oltp.position (position_id, position_name) VALUES (11, 'Left Defensive Midfield');
INSERT INTO oltp.position (position_id, position_name) VALUES (12, 'Right Midfield');
INSERT INTO oltp.position (position_id, position_name) VALUES (13, 'Right Center Midfield');
INSERT INTO oltp.position (position_id, position_name) VALUES (14, 'Center Midfield');
INSERT INTO oltp.position (position_id, position_name) VALUES (15, 'Left Center Midfield');
INSERT INTO oltp.position (position_id, position_name) VALUES (16, 'Left Midfield');
INSERT INTO oltp.position (position_id, position_name) VALUES (17, 'Right Wing');
INSERT INTO oltp.position (position_id, position_name) VALUES (18, 'Right Attacking Midfield');
INSERT INTO oltp.position (position_id, position_name) VALUES (19, 'Center Attacking Midfield');
INSERT INTO oltp.position (position_id, position_name) VALUES (20, 'Left Attacking Midfield');
INSERT INTO oltp.position (position_id, position_name) VALUES (21, 'Left Wing');
INSERT INTO oltp.position (position_id, position_name) VALUES (22, 'Right Center Forward');
INSERT INTO oltp.position (position_id, position_name) VALUES (23, 'Center Forward');
INSERT INTO oltp.position (position_id, position_name) VALUES (24, 'Left Center Forward');
INSERT INTO oltp.position (position_id, position_name) VALUES (25, 'Secondary Striker');
-- body_part
INSERT INTO oltp.body_part (body_part_id, body_part_name) VALUES (35, 'Both Hands');
INSERT INTO oltp.body_part (body_part_id, body_part_name) VALUES (36, 'Chest');
INSERT INTO oltp.body_part (body_part_id, body_part_name) VALUES (37, 'Head');
INSERT INTO oltp.body_part (body_part_id, body_part_name) VALUES (38, 'Left Foot');
INSERT INTO oltp.body_part (body_part_id, body_part_name) VALUES (39, 'Left Hand');
INSERT INTO oltp.body_part (body_part_id, body_part_name) VALUES (40, 'Right Foot');
INSERT INTO oltp.body_part (body_part_id, body_part_name) VALUES (41, 'Right Hand');
INSERT INTO oltp.body_part (body_part_id, body_part_name) VALUES (68, 'Drop Kick');
INSERT INTO oltp.body_part (body_part_id, body_part_name) VALUES (69, 'Keeper Arm');
INSERT INTO oltp.body_part (body_part_id, body_part_name) VALUES (70, 'Other');
INSERT INTO oltp.body_part (body_part_id, body_part_name) VALUES (106, 'No Touch');
-- outcome
INSERT INTO oltp.outcome (outcome_id, outcome_name) VALUES (1, 'Lost');
INSERT INTO oltp.outcome (outcome_id, outcome_name) VALUES (2, 'Success To Opposition');
INSERT INTO oltp.outcome (outcome_id, outcome_name) VALUES (3, 'Success To Team');
INSERT INTO oltp.outcome (outcome_id, outcome_name) VALUES (4, 'Won');
INSERT INTO oltp.outcome (outcome_id, outcome_name) VALUES (8, 'Complete');
INSERT INTO oltp.outcome (outcome_id, outcome_name) VALUES (9, 'Incomplete');
INSERT INTO oltp.outcome (outcome_id, outcome_name) VALUES (13, 'Lost In Play');
INSERT INTO oltp.outcome (outcome_id, outcome_name) VALUES (14, 'Lost Out');
INSERT INTO oltp.outcome (outcome_id, outcome_name) VALUES (15, 'Success');
INSERT INTO oltp.outcome (outcome_id, outcome_name) VALUES (16, 'Success In Play');
INSERT INTO oltp.outcome (outcome_id, outcome_name) VALUES (17, 'Success Out');
INSERT INTO oltp.outcome (outcome_id, outcome_name) VALUES (47, 'Claim');
INSERT INTO oltp.outcome (outcome_id, outcome_name) VALUES (48, 'Clear');
INSERT INTO oltp.outcome (outcome_id, outcome_name) VALUES (49, 'Collected Twice');
INSERT INTO oltp.outcome (outcome_id, outcome_name) VALUES (50, 'Fail');
INSERT INTO oltp.outcome (outcome_id, outcome_name) VALUES (52, 'In Play Danger');
INSERT INTO oltp.outcome (outcome_id, outcome_name) VALUES (53, 'In Play Safe');
INSERT INTO oltp.outcome (outcome_id, outcome_name) VALUES (55, 'No Touch');
INSERT INTO oltp.outcome (outcome_id, outcome_name) VALUES (56, 'Saved Twice');
INSERT INTO oltp.outcome (outcome_id, outcome_name) VALUES (58, 'Touched In');
INSERT INTO oltp.outcome (outcome_id, outcome_name) VALUES (59, 'Touched Out');
INSERT INTO oltp.outcome (outcome_id, outcome_name) VALUES (74, 'Injury Clearance');
INSERT INTO oltp.outcome (outcome_id, outcome_name) VALUES (75, 'Out');
INSERT INTO oltp.outcome (outcome_id, outcome_name) VALUES (76, 'Pass Offside');
INSERT INTO oltp.outcome (outcome_id, outcome_name) VALUES (77, 'Unknown');
INSERT INTO oltp.outcome (outcome_id, outcome_name) VALUES (96, 'Blocked');
INSERT INTO oltp.outcome (outcome_id, outcome_name) VALUES (97, 'Goal');
INSERT INTO oltp.outcome (outcome_id, outcome_name) VALUES (98, 'Off T');
INSERT INTO oltp.outcome (outcome_id, outcome_name) VALUES (99, 'Post');
INSERT INTO oltp.outcome (outcome_id, outcome_name) VALUES (100, 'Saved');
INSERT INTO oltp.outcome (outcome_id, outcome_name) VALUES (101, 'Wayward');
INSERT INTO oltp.outcome (outcome_id, outcome_name) VALUES (102, 'Injury');
INSERT INTO oltp.outcome (outcome_id, outcome_name) VALUES (103, 'Tactical');
INSERT INTO oltp.outcome (outcome_id, outcome_name) VALUES (115, 'Saved Off Target');
INSERT INTO oltp.outcome (outcome_id, outcome_name) VALUES (116, 'Saved to Post');
INSERT INTO oltp.outcome (outcome_id, outcome_name) VALUES (117, 'Punched out');
-- technique
INSERT INTO oltp.technique (technique_id, technique_name) VALUES (45, 'Diving');
INSERT INTO oltp.technique (technique_id, technique_name) VALUES (46, 'Standing');
INSERT INTO oltp.technique (technique_id, technique_name) VALUES (89, 'Backheel');
INSERT INTO oltp.technique (technique_id, technique_name) VALUES (90, 'Diving Header');
INSERT INTO oltp.technique (technique_id, technique_name) VALUES (91, 'Half Volley');
INSERT INTO oltp.technique (technique_id, technique_name) VALUES (92, 'Lob');
INSERT INTO oltp.technique (technique_id, technique_name) VALUES (93, 'Normal');
INSERT INTO oltp.technique (technique_id, technique_name) VALUES (94, 'Overhead Kick');
INSERT INTO oltp.technique (technique_id, technique_name) VALUES (95, 'Volley');
INSERT INTO oltp.technique (technique_id, technique_name) VALUES (104, 'Inswinging');
INSERT INTO oltp.technique (technique_id, technique_name) VALUES (105, 'Outswinging');
INSERT INTO oltp.technique (technique_id, technique_name) VALUES (107, 'Straight');
INSERT INTO oltp.technique (technique_id, technique_name) VALUES (108, 'Through Ball');
-- pass_height
INSERT INTO oltp.pass_height (pass_height_id, pass_height_name) VALUES (1, 'Ground Pass');
INSERT INTO oltp.pass_height (pass_height_id, pass_height_name) VALUES (2, 'Low Pass');
INSERT INTO oltp.pass_height (pass_height_id, pass_height_name) VALUES (3, 'High Pass');
-- pass_type
INSERT INTO oltp.pass_type (pass_type_id, pass_type_name) VALUES (61, 'Corner');
INSERT INTO oltp.pass_type (pass_type_id, pass_type_name) VALUES (62, 'Free Kick');
INSERT INTO oltp.pass_type (pass_type_id, pass_type_name) VALUES (63, 'Goal Kick');
INSERT INTO oltp.pass_type (pass_type_id, pass_type_name) VALUES (64, 'Interception');
INSERT INTO oltp.pass_type (pass_type_id, pass_type_name) VALUES (65, 'Kick Off');
INSERT INTO oltp.pass_type (pass_type_id, pass_type_name) VALUES (66, 'Recovery');
INSERT INTO oltp.pass_type (pass_type_id, pass_type_name) VALUES (67, 'Throw-in');
-- shot_type
INSERT INTO oltp.shot_type (shot_type_id, shot_type_name) VALUES (61, 'Corner');
INSERT INTO oltp.shot_type (shot_type_id, shot_type_name) VALUES (62, 'Free Kick');
INSERT INTO oltp.shot_type (shot_type_id, shot_type_name) VALUES (65, 'Kick Off');
INSERT INTO oltp.shot_type (shot_type_id, shot_type_name) VALUES (87, 'Open Play');
INSERT INTO oltp.shot_type (shot_type_id, shot_type_name) VALUES (88, 'Penalty');
-- duel_type
INSERT INTO oltp.duel_type (duel_type_id, duel_type_name) VALUES (10, 'Aerial Lost');
INSERT INTO oltp.duel_type (duel_type_id, duel_type_name) VALUES (11, 'Tackle');
-- goalkeeper_type
INSERT INTO oltp.goalkeeper_type (goalkeeper_type_id, goalkeeper_type_name) VALUES (25, 'Collected');
INSERT INTO oltp.goalkeeper_type (goalkeeper_type_id, goalkeeper_type_name) VALUES (26, 'Goal Conceded');
INSERT INTO oltp.goalkeeper_type (goalkeeper_type_id, goalkeeper_type_name) VALUES (27, 'Keeper Sweeper');
INSERT INTO oltp.goalkeeper_type (goalkeeper_type_id, goalkeeper_type_name) VALUES (28, 'Penalty Conceded');
INSERT INTO oltp.goalkeeper_type (goalkeeper_type_id, goalkeeper_type_name) VALUES (29, 'Penalty Saved');
INSERT INTO oltp.goalkeeper_type (goalkeeper_type_id, goalkeeper_type_name) VALUES (30, 'Punch');
INSERT INTO oltp.goalkeeper_type (goalkeeper_type_id, goalkeeper_type_name) VALUES (31, 'Save');
INSERT INTO oltp.goalkeeper_type (goalkeeper_type_id, goalkeeper_type_name) VALUES (32, 'Shot Faced');
INSERT INTO oltp.goalkeeper_type (goalkeeper_type_id, goalkeeper_type_name) VALUES (33, 'Shot Saved');
INSERT INTO oltp.goalkeeper_type (goalkeeper_type_id, goalkeeper_type_name) VALUES (34, 'Smother');
INSERT INTO oltp.goalkeeper_type (goalkeeper_type_id, goalkeeper_type_name) VALUES (109, 'Penalty Saved to Post');
INSERT INTO oltp.goalkeeper_type (goalkeeper_type_id, goalkeeper_type_name) VALUES (110, 'Saved to Post');
INSERT INTO oltp.goalkeeper_type (goalkeeper_type_id, goalkeeper_type_name) VALUES (113, 'Shot Saved Off Target');
INSERT INTO oltp.goalkeeper_type (goalkeeper_type_id, goalkeeper_type_name) VALUES (114, 'Shot Saved to Post');
-- card_type
INSERT INTO oltp.card_type (card_type_id, card_type_name) VALUES (5, 'Red Card');
INSERT INTO oltp.card_type (card_type_id, card_type_name) VALUES (6, 'Second Yellow');
INSERT INTO oltp.card_type (card_type_id, card_type_name) VALUES (7, 'Yellow Card');
-- formation
INSERT INTO oltp.formation (formation_id, formation_name) VALUES (343, '3-4-3');
INSERT INTO oltp.formation (formation_id, formation_name) VALUES (352, '3-5-2');
INSERT INTO oltp.formation (formation_id, formation_name) VALUES (433, '4-3-3');
INSERT INTO oltp.formation (formation_id, formation_name) VALUES (442, '4-4-2');
INSERT INTO oltp.formation (formation_id, formation_name) VALUES (451, '4-5-1');
INSERT INTO oltp.formation (formation_id, formation_name) VALUES (532, '5-3-2');
INSERT INTO oltp.formation (formation_id, formation_name) VALUES (541, '5-4-1');
INSERT INTO oltp.formation (formation_id, formation_name) VALUES (3142, '3-1-4-2');
INSERT INTO oltp.formation (formation_id, formation_name) VALUES (3232, '3-2-3-2');
INSERT INTO oltp.formation (formation_id, formation_name) VALUES (3412, '3-4-1-2');
INSERT INTO oltp.formation (formation_id, formation_name) VALUES (3421, '3-4-2-1');
INSERT INTO oltp.formation (formation_id, formation_name) VALUES (3511, '3-5-1-1');
INSERT INTO oltp.formation (formation_id, formation_name) VALUES (4132, '4-1-3-2');
INSERT INTO oltp.formation (formation_id, formation_name) VALUES (4141, '4-1-4-1');
INSERT INTO oltp.formation (formation_id, formation_name) VALUES (4213, '4-2-1-3');
INSERT INTO oltp.formation (formation_id, formation_name) VALUES (4222, '4-2-2-2');
INSERT INTO oltp.formation (formation_id, formation_name) VALUES (4231, '4-2-3-1');
INSERT INTO oltp.formation (formation_id, formation_name) VALUES (4312, '4-3-1-2');
INSERT INTO oltp.formation (formation_id, formation_name) VALUES (4321, '4-3-2-1');
INSERT INTO oltp.formation (formation_id, formation_name) VALUES (4411, '4-4-1-1');
INSERT INTO oltp.formation (formation_id, formation_name) VALUES (5221, '5-2-2-1');
INSERT INTO oltp.formation (formation_id, formation_name) VALUES (31222, '3-1-2-2-2');
INSERT INTO oltp.formation (formation_id, formation_name) VALUES (32122, '3-2-1-2-2');
INSERT INTO oltp.formation (formation_id, formation_name) VALUES (32221, '3-2-2-2-1');
INSERT INTO oltp.formation (formation_id, formation_name) VALUES (41131, '4-1-1-3-1');
INSERT INTO oltp.formation (formation_id, formation_name) VALUES (41212, '4-1-2-1-2');
INSERT INTO oltp.formation (formation_id, formation_name) VALUES (41221, '4-1-2-2-1');
INSERT INTO oltp.formation (formation_id, formation_name) VALUES (42121, '4-2-1-2-1');
INSERT INTO oltp.formation (formation_id, formation_name) VALUES (42211, '4-2-2-1-1');
INSERT INTO oltp.formation (formation_id, formation_name) VALUES (312112, '3-1-2-1-1-2');
